# Meta

title:         "Planswell: a Living Style Guide based on Bulma"
description:   "Bulma is an open source CSS framework based on Flexbox and built with Sass. It's 100% responsive, fully modular, and available for free."

# Build

markdown:      kramdown
permalink:     pretty
url:           http://localhost:4010
fontawesome:   https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css

# Variables

documentation: "/documentation/overview/start/"
download:      https://github.com/jgthms/bulma/archive/0.4.2.zip
github:        https://github.com/jgthms/bulma
version:       0.4.2
